name = "forwardr-webhook"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "FAILED_UPDATES"
id = "b4a7291fde4c41d58991047216d7affe"

[[kv_namespaces]]
binding = "CREDENTIALS"
id = "f490887adf624e629612fdeddf76212a"

# Cron trigger: process the queue every 5 hours
[triggers]
crons = ["0 */5 * * *"]
